// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function Reset() {
  return window['go']['app']['App']['Reset']();
}

export function SelectLogFile() {
  return window['go']['app']['App']['SelectLogFile']();
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StartTracking(arg1) {
  return window['go']['app']['App']['StartTracking'](arg1);
}

export function StartTrackingWithOptions(arg1, arg2) {
  return window['go']['app']['App']['StartTrackingWithOptions'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function Stop() {
  return window['go']['app']['App']['Stop']();
}

export function UIState() {
  return window['go']['app']['App']['UIState']();
}
