// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';

export function GetState():Promise<app.UIState>;

export function Reset():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartTracking(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;

export function UIState():Promise<app.UIState>;
